(function (global) {
  global.SiteCopy = {
    commonRules: [
      { selector: '.nav-menu .nav-item a[href="index.html"]', index: 0, text: '首页' },
      { selector: '.nav-menu .nav-item a[href="business.html"]', index: 0, text: '主营业务' },
      { selector: '.nav-menu .nav-item a[href="projects.html"]', index: 0, text: '项目案例' },
      { selector: '.nav-menu .nav-item a[href="news.html"]', index: 0, text: '行业资讯' },
      { selector: '.nav-menu .nav-item a[href="about.html"]', index: 0, text: '关于我们' },

      { selector: '.m-drawer a[href="index.html"]', text: '首页' },
      { selector: '.m-drawer a[href="business.html"]', text: '主营业务' },
      { selector: '.m-drawer a[href="news.html"]', text: '行业资讯' },
      { selector: '.m-drawer a[href="projects.html"],.m-drawer a[href="../projects.html"]', text: '项目案例' },
      { selector: '.m-drawer a[href="about.html"],.m-drawer a[href="../about.html"]', text: '关于我们' },

      { selector: '.footer-phone-label', text: '咨询电话' },
      { selector: '.m-footer-label', index: 0, text: '咨询电话' },
      { selector: '.mb-footer-label', index: 0, text: '咨询电话' },
      { selector: '.mp-footer-label', index: 0, text: '咨询电话' },
      { selector: '.mn-footer-label', index: 0, text: '咨询电话' },
      { selector: '.ma-footer-label', index: 0, text: '咨询电话' },
      { selector: '.footer-phone,.m-footer-phone,.mb-footer-phone,.mp-footer-phone,.mn-footer-phone,.ma-footer-phone', text: '028-85120989' },
      { selector: '.footer-addr-label', text: '公司地址' },
      { selector: '.m-footer-label', index: 1, text: '公司地址' },
      { selector: '.mb-footer-label', index: 1, text: '公司地址' },
      { selector: '.mp-footer-label', index: 1, text: '公司地址' },
      { selector: '.mn-footer-label', index: 1, text: '公司地址' },
      { selector: '.ma-footer-label', index: 1, text: '公司地址' },
      {
        selector: '.m-footer-addr,.footer-addr,.mb-footer-addr,.mp-footer-addr,.mn-footer-addr,.ma-footer-addr',
        text: '成都市高新区吉庆三路333号蜀都中心2期1栋',
      },
      {
        selector: '.footer-copy,.m-footer-copy,.mb-footer-copy,.mp-footer-copy,.mn-footer-copy,.ma-footer-copy',
        text: '©2019成都申洲科技有限责任公司 版权所有',
      },
    ],
    pages: {
      index: [
        { selector: '.hero-title', text: '懂您所需，做您所想' },
        { selector: '.m-hero-content h1', html: '懂您所需，做您所想' },
        { selector: '.hero-desc,.m-hero-content p', html: '以全栈式科技服务，<br />为创意赋能，为用户创造价值。' },
        { selector: '.biz-section .sec-title,.m-biz .m-sec-title', html: '聚焦创新技术的研发与应用' },
        { selector: '.biz-section .sec-en,.m-biz .m-sec-en', text: 'Main business' },
        { selector: '.biz-grid .biz-name,.m-biz-card span', index: 0, text: '系统集成' },
        { selector: '.biz-grid .biz-name,.m-biz-card span', index: 1, text: '软件平台开发' },
        { selector: '.biz-grid .biz-name,.m-biz-card span', index: 2, text: '数据分析应用' },
        { selector: '.biz-grid .biz-name,.m-biz-card span', index: 3, text: '三维数字服务' },
        { selector: '.val-section .sec-title,.m-val .m-sec-title', text: '持续为客户创造价值' },
        { selector: '.val-section .sec-en,.m-val .m-sec-en', text: 'Project Case' },
        { selector: '.val-card .val-title,.m-val-card .m-val-title', index: 0, text: '低空经济' },
        { selector: '.val-card .val-title,.m-val-card .m-val-title', index: 1, text: '政法委' },
        { selector: '.val-card .val-title,.m-val-card .m-val-title', index: 2, text: '公安' },
        { selector: '.val-card .val-title,.m-val-card .m-val-title', index: 3, text: '法院' },
        { selector: '.val-card .val-title,.m-val-card .m-val-title', index: 4, text: '司法' },
        { selector: '.val-card .val-desc,.m-val-card .m-val-desc', index: 0, html: '以数字科技成就<br />最好的低空服务' },
        { selector: '.val-card .val-desc,.m-val-card .m-val-desc', index: 1, html: '优化政法工作流程<br />提升社会治理能力' },
        { selector: '.val-card .val-desc,.m-val-card .m-val-desc', index: 2, html: '深化科技赋能<br />提升新质公安战斗力' },
        {
          selector: '.val-card .val-desc,.m-val-card .m-val-desc',
          index: 3,
          html: '提升审判效率<br />强化执行工作<br />优化诉讼服务<br />实现司法管理智能化',
        },
        { selector: '.val-card .val-desc,.m-val-card .m-val-desc', index: 4, html: '科技赋能<br />提升案件办理质效' },
        { selector: '.val-card .val-btn,.m-val-more .m-val-title', text: '了解更多 →' },
        { selector: '.vision-h,.m-vision-blue h2', html: '成为一流<br />数字化服务商' },
        { selector: '.vision-btn,.m-vision-btn', text: '了解详情 →' },
      ],
      business: [
        { selector: '.biz-hero-inner h1,.mb-hero-content h1,.m-nav-title', text: '主营业务' },
        {
          selector: '.biz-hero-inner p,.mb-hero-content p',
          text: '聚焦于创新技术的研发与应用，在软件服务、平台搭建及定制化方案展现出专业的技术水准。',
        },
        { selector: '#xtjc .sec-title,.mb-sec-title', index: 0, text: '系统集成' },
        { selector: '#xtjc .sec-en,.mb-sec-en', index: 0, text: 'SYSTEM INTEGRATION' },
        { selector: '.biz-item-title,.mb-item-title', index: 0, text: '智慧机房' },
        { selector: '.biz-item-desc,.mb-item-desc', index: 0, text: '具有自动监测、远程运维、自主报警、数据管理等功能。' },
        { selector: '.biz-item-title,.mb-item-title', index: 1, text: '综合布线' },
        { selector: '.biz-item-desc,.mb-item-desc', index: 1, text: '将语音、网络、交换及其他控制设备与信息管理系统融汇贯通，实现实时交互。' },
        { selector: '.biz-item-title,.mb-item-title', index: 2, text: '智慧诉服' },
        { selector: '.biz-item-desc,.mb-item-desc', index: 2, text: '完善诉讼服务平台，构建高效便民、智慧精准的诉讼服务体系。' },
        { selector: '.biz-item-title,.mb-item-title', index: 3, text: '无人值守钥匙管理系统' },
        {
          selector: '.biz-item-desc,.mb-item-desc',
          index: 3,
          text: '推进党政机关厉行节约反对浪费，建设节约型机关，改革公务用车制度，规范公务用车管理，有效降低用车成本。',
        },
        { selector: '.biz-item-title,.mb-item-title', index: 4, text: '智慧档案管理系统' },
        {
          selector: '.biz-item-desc,.mb-item-desc',
          index: 4,
          text: '实现纸质档案数字化、电子档案管理全流程，支持OCR识别、智能分类和长期保存，满足合规要求。',
        },
        { selector: '.biz-dark-left h2,.mb-dark-h2', text: '软件平台开发' },
        { selector: '.biz-dark-left .en,.mb-dark-en', text: 'Software platform development' },
        { selector: '.mb-dark-label', text: '一站式解决方案' },
        {
          selector: '.mb-dark-desc',
          text: '根据用户需求，提供定制化解决方案，软件平台开发涉及 构建一套完整的、模块化的解决方案， 以支持软件和基于软件的服务开发。',
        },
        { selector: '.biz-data-left h2', text: '数据分析应用' },
        { selector: '.mb-sec-title', index: 1, text: '数据分析应用' },
        { selector: '.biz-data-left .en', text: 'Data analysis application' },
        { selector: '.mb-sec-en', index: 1, text: 'Data analysis application' },
        {
          selector: '.biz-data-left p,.mb-data-desc',
          text: '基于公司大数据咨询服务体系和数据治理系统实施能力，可帮助建立数据治理体系，实现企业在数据规模大、关系错综复杂情况下对数据的有效分析利用。主要解决数据质量及安全共享问题，帮助管理和有效利用数据资产。',
        },
        { selector: '.biz-data-card,.mb-data-card', index: 1, text: '全要素多源数据编制融合' },
        { selector: '.biz-3d-section .sec-title', text: '三维数字服务' },
        { selector: '.mb-3d-sec-header .mb-sec-title', text: '三维数字服务' },
        { selector: '.biz-3d-section .sec-en', text: '3D DIGITAL SERVICE' },
        { selector: '.mb-3d-sec-header .mb-sec-en', text: '3D DIGITAL SERVICE' },
        { selector: '.biz-3d-title,.mb-3d-title', index: 0, text: '三维立体全景' },
        {
          selector: '.biz-3d-desc,.mb-3d-desc',
          index: 0,
          text: '提供三维模型、三维设计、三维可视化等相关领域咨询服务。涉及三维建模技术、三维渲染技术、三维动画制作等多个方面。',
        },
        { selector: '.biz-3d-title,.mb-3d-title', index: 1, text: '地形倾斜摄影处理' },
        {
          selector: '.biz-3d-desc,.mb-3d-desc',
          index: 1,
          text: '倾斜摄影测量技术（Oblique Photogrammetry）是一种通过使用倾斜角度相机拍摄图像的方法来进行测量和建模的技术。',
        },
        { selector: '.biz-3d-title,.mb-3d-title', index: 2, text: '三维建模' },
        {
          selector: '.biz-3d-desc,.mb-3d-desc',
          index: 2,
          text: '基于科学的设计方法与技术服务路线，依托实际需求定制建模，通过数据预处理和配准处理等操作，进一步提取有效数据，进行曲面和实体构造，最终得到三维模型。',
        },
      ],
      projects: [
        { selector: '.proj-hero-inner h1,.mp-hero-content h1,.m-nav-title', text: '项目案例' },
        { selector: '.proj-hero-inner p,.mp-hero-content p', text: '持续为客户创造价值' },
        { selector: '.proj-zhengfa-left h2', text: '政法委' },
        { selector: '.mp-sec-title', index: 0, text: '政法委' },
        { selector: '.proj-zhengfa-left .en', text: 'Politics and Law Committee' },
        { selector: '.mp-sec-en', index: 0, text: 'Politics and Law Committee' },
        { selector: '.proj-zhengfa-left h4,.mp-zfw-title', text: '多元纠纷化解平台' },
        {
          selector: '.proj-zhengfa-left p,.mp-sec-desc',
          text: '通过服务号+小程序，构建多元纠纷化解体系，实时为调解人员和申请人提醒，分为调解申请、指派调解、调解办理、结果反馈、法律法规、法治宣传等。',
        },
        { selector: '.proj-dark-left h2', text: '公安' },
        { selector: '.mp-sec-title', index: 1, text: '公安' },
        { selector: '.proj-dark-left .en', text: 'Public Security' },
        { selector: '.mp-sec-en', index: 1, text: 'Public Security' },
        { selector: '.timeline-item-text,.mp-dark-desc-ga', index: 0, text: '无人机作战一体化平台' },
        { selector: '.proj-cards-section .sec-title', text: '法院' },
        { selector: '.mp-sec-title', index: 2, text: '法院' },
        { selector: '.proj-cards-section .sec-en', text: 'COURT' },
        { selector: '.mp-sec-en', index: 2, text: 'COURT' },
        { selector: '.proj-card-label,.mp-card span', index: 0, text: '智慧诉服' },
        { selector: '.proj-card-label,.mp-card span', index: 1, text: '大数据决策分析系统' },
        { selector: '.proj-card-label,.mp-card span', index: 2, text: '智慧警务' },
        { selector: '.proj-card-label,.mp-card span', index: 3, text: '执行全景指挥' },
        { selector: '.proj-card-label,.mp-card span', index: 4, text: '数字化会议' },
        { selector: '.proj-sifa .sec-title', text: '司法' },
        { selector: '.mp-sec-title', index: 3, text: '司法' },
        { selector: '.proj-sifa .sec-en', text: 'JUDICIARY' },
        { selector: '.mp-sec-en', index: 3, text: 'JUDICIARY' },
        { selector: '.proj-sifa-text h3,.mp-sifa-text h2', text: '行政复议智慧听证系统' },
        { selector: '.proj-sifa-text p,.mp-sifa-text h3', index: 0, text: '数字赋能 智慧司法' },
        {
          selector: '.proj-sifa-text p,.mp-sifa-text p',
          index: 1,
          text: '科技赋能提升案件办理质效，全面推进行政复议体制改革与法治政府建设',
        },
        { selector: '.sec-center .sec-title', index: 2, text: '低空平台' },
        { selector: '.sec-center .sec-en', index: 2, text: 'Low altitude' },
        { selector: '.proj-dijing-inner h2,.mp-dijing-h2', text: '低空"政"能量' },
        { selector: '.proj-dijing-inner p,.mp-dijing-desc', text: 'Low altitude government affairs' },
      ],
      about: [
        { selector: '.about-hero-inner h1,.m-nav-title', text: '关于我们' },
        {
          selector: '.about-hero-inner p,.ma-intro p',
          index: 0,
          text: '成都申洲科技有限责任公司是一家国家级高新技术企业、双软企业、省专精特新企业和纳税信用等级A级企业。',
        },
        {
          selector: '.about-hero-inner p,.ma-intro p',
          index: 1,
          text: '申洲科技以创新的科技与高水平的项目管理经验凝结为企业核心，形成以系统集成、软件平台开发、三维数字服务、大数据分析应用为主营业务的高新技术企业和专精特新中小企业，构建从物联网技术到业务流程的整体解决方案，服务于新时代智慧政府、智慧城市、智慧工程的建设和运维。为提高政务管理效率，增强城市综合竞争力，促进人民美好生活品质贡献申洲力量。',
        },
        { selector: '.culture-section .sec-title,.ma-culture .ma-sec-title', text: '企业文化' },
        { selector: '.culture-section .sec-en,.ma-culture .ma-sec-en', text: 'COMPANY CULTURE' },
        { selector: '.honor-section .sec-title,.ma-honor .ma-sec-title', text: '荣誉资质' },
        { selector: '.honor-section .sec-en,.ma-honor .ma-sec-en', text: 'HONOR AND QUALIFICATIONS' },
        { selector: '.contact-section .sec-title,.ma-contact .ma-sec-title', text: '联系我们' },
        { selector: '.contact-section .sec-en,.ma-contact .ma-sec-en', text: 'CONTACT US' },
        { selector: '.contact-section .sec-center p,.ma-contact-sub', text: '如果有任何问题请联系我们，我们将竭诚为您服务' },
        { selector: '.contact-label,.ma-contact-label', index: 0, text: '联系电话' },
        { selector: '.contact-label,.ma-contact-label', index: 1, text: '网址' },
        { selector: '.contact-label,.ma-contact-label', index: 2, text: '地址' },
      ],
      news: [
        { selector: '.news-banner-inner h1,.m-nav-title', text: '行业资讯' },
        { selector: '.news-banner-inner p,.mn-banner-desc', text: '了解最新行业资讯，掌握最新行业动态' },
        { selector: '.news-tab,.mn-tab', index: 0, text: '法院' },
        { selector: '.news-tab,.mn-tab', index: 1, text: '司法' },
        { selector: '.news-tab,.mn-tab', index: 2, text: '政法委' },
      ],
      'biz-detail': [
        { selector: '.sidebar-cat,.m-nav-title', text: '系统集成' },
        { selector: '.detail-title,.md-title', text: '智慧机房' },
        {
          selector: '.detail-section-desc,.md-desc',
          text: '智慧机房是指具有自动监测、远程运维、自主预警、数据管理等功能的机房。',
        },
      ],
    },
  };
})(typeof window !== 'undefined' ? window : this);
